Hotfix/T44
fga-eps-mds/2019.1-Ludum pull request #122
Opened 2019-05-11 01:25 UTC by lucasgandac

## Descrição
Nesse Pull Request (PR) foram resolvidos os seguintes aspectos:
  - Refatoração dos diálogos.

## Issue Correspondente
![T44 - Refatorar os diálogos do bot de acordo com recomendações da R1](https://github.com/fga-eps-mds/2019.1-Ludum/issues/120)

## Tipo de mudança
- [x] **Bugfix** (mudança que corrige um problema)
- [ ] **Nova funcionalidade** (mudança que adiciona uma funcionalidade)
- [ ] **Mudança de funcionalidade** (corrige ou adiciona recursos de uma funcionalidade que já existe)

## Checklist
Esse PR atende os requisitos abaixo:
- [x]  Atender a folha de estilo do código;
- [x] O conteúdo das mensagens deve estar conforme a personalidade definida para ele;
- [x] Corrigir os erros de português;

## Comentários
Nenhum.

2019-05-11 22:02 UTC, guilhermesiqueira requested changes
Está interação foi algo que foi reclamado na R1 e que não foi corrigido neste PR. Deve-se remover o que está representado pelo retângulo vermelho e, ao invés da mensagem destacada pelo retângulo amarelo, deve-se falar ali que a funcionalidade ainda não foi implementada. O mesmo ocorre quando o usuário seleciona a opção de materiais e links.

![Captura de Tela 2019-05-11 às 18 49 52](https://user-images.githubusercontent.com/30915713/57575358-46ac0e80-741f-11e9-81d3-3cdd78cb24bc.png)

2019-05-11 22:22 UTC, guilhermesiqueira commented
Onde está destacado com uma linha vermelha, conforme foi falado no PR #106, não se deve assumir que a distribuição Linux que o usuário está utilizando é baseada em debian. As instruções permanecem as mesmas deste comentário [aqui](https://github.com/fga-eps-mds/2019.1-Ludum/pull/106#pullrequestreview-232213760), entretanto, deve-se redirecionar o usuário para a página de instalação do próprio Python. O link onde pode-se baixar o Python se encontra [aqui](https://www.python.org/downloads/). Também deve-se remover as instruções para usuário de macOS, pois as instruções para instalação do Python também podem ser achadas na comunidade do Python.

Deve-se remover estás aspas onde há o retângulo amarelo.

O retângulo azul destaca o local onde o Ludum assume que o usuário está utilizando o Visual Studio Code. Não se deve assumir isso.

![Captura de Tela 2019-05-11 às 18 51 16](https://user-images.githubusercontent.com/30915713/57575472-f635b080-7420-11e9-8ce8-5bf673eb2aa4.png)

2019-05-11 22:27 UTC, guilhermesiqueira commented
Após a última mensagem, deve-se informar o usuário que ainda não foram implementadas funcionalidades para o prosseguimento da conversa, pois do jeito que está o Ludum para de responder no meio da interação, dando a entender que o bot parou de funcionar. 

<img width="850" alt="Captura de Tela 2019-05-11 às 18 51 43" src="https://user-images.githubusercontent.com/30915713/57575534-790b3b00-7422-11e9-9e9d-d479c4505733.png">

2019-05-12 23:59 UTC, lucasgandac commented
Modificações solicitadas foram realizadas

2019-05-13 15:41 UTC, guilhermesiqueira requested changes
Conforme ilustrado na imagem abaixo, o Ludum responde que a funcionalidade não foi implementada apenas quando selecionada a opção do tutorial difícil. Deve-se apresentar a mensagem que a funcionalidade não foi implementada quando um tutorial fácil ou médio for selecionado. 
<img width="847" alt="Captura de Tela 2019-05-13 às 12 33 54" src="https://user-images.githubusercontent.com/30915713/57634688-2fcefe80-757c-11e9-96be-4166fb22ee04.png">

2019-05-13 15:50 UTC, guilhermesiqueira commented
A mensagem destacada pelo retângulo vermelho não deve aparecer neste contexto, pois ela aparece quando o usuário diz que já possui o Python instalado no computador:
![Captura de Tela 2019-05-13 às 12 35 24](https://user-images.githubusercontent.com/30915713/57634971-ae2ba080-757c-11e9-9377-254c2e59370b.png)

Como mostra a imagem em sequência, com a mensagem destacada pelo retângulo amarelo:

![Captura de Tela 2019-05-13 às 12 37 00](https://user-images.githubusercontent.com/30915713/57635237-23977100-757d-11e9-87ea-7083e9edb268.png)

Como alternativa ao que está destacado pelo retângulo vermelho, o Ludum deve perguntar ao usuário se o bot pode prosseguir com os próximos passos, e após a resposta do usuário que o Ludum deverá perguntar se o usuário possui algum editor de texto instalado.

2019-05-13 15:55 UTC, guilhermesiqueira commented
O ponto comentado [aqui](https://github.com/fga-eps-mds/2019.1-Ludum/pull/122#issuecomment-491548507) ainda não foi corrigido, pois o Ludum ainda para de responder do nada, conforme ilustra a imagem abaixo:

![Captura de Tela 2019-05-13 às 12 37 00](https://user-images.githubusercontent.com/30915713/57635804-4a09dc00-757e-11e9-811d-1366e2835aeb.png)

2019-05-13 16:00 UTC, guilhermesiqueira commented
Por favor, corrija o exposto!

2019-05-13 16:14 UTC, lucasgandac commented
Caso o usuário responda que não pode prosseguir para o próximo passo, qual deverá ser a resposta do bot ?

2019-05-13 16:22 UTC, guilhermesiqueira commented
> Caso o usuário responda que não pode prosseguir para o próximo passo, qual deverá ser a resposta do bot ?

Faça o Ludum redirecionar o usuário para o guia para iniciantes do Python, onde há informações mais detalhadas sobre a instalação: https://wiki.python.org/moin/BeginnersGuide/Download

Após esta mensagem, deve-se enviar a mesma mensagem pedindo permissão para prosseguimento. Caso o usuário informar que não deseja prosseguir, dispare novamente a mensagem contendo o link do guia para iniciantes em Python.

2019-05-13 20:55 UTC, lucasgandac commented
A mensagem de "podemos prosseguir com os proximos passos ?", deve ser implementada so para o python, ou para as outras partes como editor de texto e pygame tambem ?

2019-05-13 21:07 UTC, guilhermesiqueira commented
> A mensagem de "podemos prosseguir com os proximos passos ?", deve ser implementada so para o python, ou para as outras partes como editor de texto e pygame tambem ?

Deve ser implementada para o Python, editor de texto e Pygame

2019-05-14 05:12 UTC, lucasgandac commented
As alteracoes necessarias foram feitas

2019-05-14 14:50 UTC, guilhermesiqueira approved these changes
Tudo ok com o PR!

2019-05-14 14:51 UTC, merged