US13 - Selecionar complexidade do jogo no tutorial
fga-eps-mds/2019.1-Ludum pull request #127
Opened 2019-05-14 05:23 UTC by Wictorgirardi

## Descrição
Nesse Pull Request (PR) foram resolvidos os seguintes aspectos:
  - Adicionado inline keyboard commands(botões) para selecionar os níveis de dificuldade do tutorial.

## Issue Correspondente
![US13 - Selecionar complexidade do jogo no tutorial](https://github.com/fga-eps-mds/2019.1-Ludum/issues/65)

## Tipo de mudança
- [ ] **Bugfix** (mudança que corrige um problema)
- [ ] **Nova funcionalidade** (mudança que adiciona uma funcionalidade)
- [X] **Mudança de funcionalidade** (corrige ou adiciona recursos de uma funcionalidade que já existe)

## Checklist
Esse PR atende os requisitos abaixo:
- [x]  Atender a folha de estilo do código;
- [x] O conteúdo das mensagens deve estar conforme a personalidade definida para ele;
- [x] Corrigir os erros de português;

## Comentários
Nenhum.

2019-05-14 18:57 UTC, Wictorgirardi commented
Merge e conflitos solucionados!

2019-05-15 00:31 UTC, guilhermesiqueira requested changes
Nas dificuldades dos jogos, deve-se colocar:
- Padawan
- Jedi
- Tutoriais da Comunidade
e não "fácil", "médio" e "difícil". Além disso, deve-se acrescentar um terceiro botão contemplando os tutoriais da comunidade que serão posteriormente adicionados.

<img width="453" alt="Captura de Tela 2019-05-14 às 21 27 46" src="https://user-images.githubusercontent.com/30915713/57740623-26828680-768f-11e9-91a4-443c05d3e2a9.png">

2019-05-15 14:52 UTC, Wictorgirardi commented
Mudanças requisitadas efetuadas!

2019-05-15 22:40 UTC, guilhermesiqueira approved these changes

2019-05-15 22:41 UTC, merged