US24 - Exibir lista de recomendações de ferramentas de desenvolvimento
fga-eps-mds/2019.1-Ludum pull request #139
Opened 2019-05-26 23:09 UTC by Wictorgirardi

## Descrição
Nesse Pull Request (PR) foram resolvidos os seguintes aspectos:
  - Sugestão de ferramentas que podem ser úteis ao desenvolvimento;
  - Correção de pequenos erros.

## Issue Correspondente
US24 - Exibir lista de recomendações de ferramentas de desenvolvimento(https://github.com/fga-eps-mds/2019.1-Ludum/issues/125)

## Tipo de mudança
- [ ] **Bugfix** (mudança que corrige um problema)
- [ ] **Nova funcionalidade** (mudança que adiciona uma funcionalidade)
- [x] **Mudança de funcionalidade** (corrige ou adiciona recursos de uma funcionalidade que já existe)

## Checklist
Esse PR atende os requisitos abaixo:
- [x] O código deve atender a folha de estilo;
- [x] O conteúdo das mensagens está conforme a [personalidade](https://fga-eps-mds.github.io/2019.1-Ludum/#/personalidade-ludum) definida para ele;
- [x] O Ludum deve estar perguntando acerca do Python e PyGame e fornecendo as orientações necessárias;
- [x] O Ludum deve estar exibindo uma lista de recomendações de ferramentas de desenvolvimento.

## Comentários
Alguma informação complementar necessária para melhor compreensão.

2019-05-28 02:18 UTC, gabrielademoraes commented
![BotAmbiente](https://user-images.githubusercontent.com/30664415/58446051-93594000-80d5-11e9-883f-59bc566cebd8.png)

Essa mensagem não deixa explícito qual seria o próximo passo.

2019-05-28 02:21 UTC, gabrielademoraes commented
![BotAmbiente2](https://user-images.githubusercontent.com/30664415/58446115-d9ae9f00-80d5-11e9-921c-1c99b1e3ee51.png)

Esse questionamento "Já podemos seguir para o próximo passo?" não ficou bem localizado.

2019-05-28 02:24 UTC, gabrielademoraes commented
![BotAmbiente3](https://user-images.githubusercontent.com/30664415/58446217-37db8200-80d6-11e9-8d43-48ef1490411f.png)

Essa parte ficou muito carregada em relação ao texto e pode causar uma certa confusão. Creio que um fluxo mais legal seria perguntar sobre o python, depois sobre a pygame e por ultimo sugerir ferramentas, e também quebrar em mensagens menores, se possível.

2019-05-28 02:29 UTC, gabrielademoraes commented
Outro aspecto interessante seria quando o fluxo chegar ao fim, exibir o menu inicial.

2019-05-28 02:34 UTC, gabrielademoraes requested changes
Considerar as recomendações dadas, por favor.

2019-05-28 20:28 UTC, Wictorgirardi commented
Correções realizadas! Por favor re avaliar o PR :)

2019-05-29 02:38 UTC, LucasPenido requested changes
As perguntas relacionadas à continuidade da instalação deveriam ficar abaixo dos links.

2019-05-29 04:37 UTC, Wictorgirardi commented
Correções mais uma vez realizadas! Reavaliar PR

2019-05-29 05:24 UTC, LucasPenido approved these changes

2019-05-29 05:26 UTC, LucasPenido commented
Correção feitas devidamente, tudo certo com o PR.

2019-05-29 05:26 UTC, merged