US15 - Aprender a criar um jogo de maior complexidade
fga-eps-mds/2019.1-Ludum pull request #149
Opened 2019-05-28 23:13 UTC by thallysbraz

## Descrição
Nesse Pull Request (PR) foram resolvidos os seguintes aspectos:
  - Implementação do tutorial de nível médio.

## Issue Correspondente
[US15 - Aprender a criar um jogo de baixa complexidade](https://github.com/fga-eps-mds/2019.1-Ludum/issues/64)

## Tipo de mudança
- [ ] **Bugfix** (mudança que corrige um problema)
- [x] **Nova funcionalidade** (mudança que adiciona uma funcionalidade)
- [ ] **Mudança de funcionalidade** (corrige ou adiciona recursos de uma funcionalidade que já existe)

## Checklist
Esse PR atende os requisitos abaixo:
- [x] Antes de iniciar o tutorial, o Ludum deve informar o usuário acerca da importância de conferir a seção de **Ambiente** antes de iniciar um tutorial;
- [x] O Ludum deve contextualizar o usuário sobre o jogo que será implementado (regras, curiosidades, entre outros);
- [x] O Ludum deve ensinar passo a passo como desenvolver o jogo por meio de mensagens e exemplos de código;
- [x] Nos intervalos entre os passos, o Ludum deve pedir a confirmação do usuário para continuação do tutorial; 

## Comentários
--

2019-06-02 00:00 UTC, guilhermesiqueira requested changes
Ainda há erros de compilação no PR. Por favor, corrija! 
<img width="988" alt="Captura de Tela 2019-06-01 às 20 59 48" src="https://user-images.githubusercontent.com/30915713/58754911-3c29e580-84b0-11e9-8d04-ee65af95feaa.png">

2019-06-03 02:17 UTC, guilhermesiqueira commented
Não se deve falar "Pronto ou pronto", pois significa a mesma coisa. O Ludum deve apenas perguntar "Podemos prosseguir?"
<img width="853" alt="Captura de Tela 2019-06-02 às 23 13 42" src="https://user-images.githubusercontent.com/30915713/58771787-651fa880-858c-11e9-8cb4-25897d1ff37a.png">

2019-06-03 02:18 UTC, guilhermesiqueira commented
Na imagem abaixo há fragmentos de código que se confundem com o texto da mensagem. Deve-se colocar este fragmento de código entre três crases (`).
<img width="497" alt="Captura de Tela 2019-06-02 às 23 15 00" src="https://user-images.githubusercontent.com/30915713/58771823-9ef0af00-858c-11e9-81f4-a190645e0cc4.png">

2019-06-03 02:28 UTC, thallysbraz commented
A ideia a principio era justamente essa de usar as três crases (`), mas tentei de vários jeitos e o Rasa não mostra igual em conversa normal. Tentei de vários jeitos diferentes.

2019-06-03 02:30 UTC, guilhermesiqueira commented
No final do tutorial o Ludum se confunde e responde algo não relacionado ao tutorial em execução. 
<img width="854" alt="Captura de Tela 2019-06-02 às 23 22 31" src="https://user-images.githubusercontent.com/30915713/58772053-b2504a00-858d-11e9-8b49-728f0c3fc855.png">

2019-06-03 02:34 UTC, guilhermesiqueira commented
> A ideia a principio era justamente essa de usar as três crases (`), mas tentei de vários jeitos e o Rasa não mostra igual em conversa normal. Tentei de vários jeitos diferentes.

Visto esta limitação, retire as crases de partes do tutorial que ainda as possuem, como ilustrado na imagem abaixo:

<img width="857" alt="Captura de Tela 2019-06-02 às 23 33 26" src="https://user-images.githubusercontent.com/30915713/58772362-f42dc000-858e-11e9-8e5f-e40f8efb7d2a.png">

2019-06-03 02:40 UTC, guilhermesiqueira requested changes
Por favor, realize as mudanças apontadas!

2019-06-03 02:40 UTC, guilhermesiqueira commented on rasa/credentials.yml
>  telegram:
O arquivo rasa/credentials.yml não deve ser commitado de forma modificada em hipótese alguma. Por favor, deixe-o conforme abaixo:

```python
telegram:
  access_token: ${TELEGRAM_TOKEN}
  verify: ${TELEGRAM_BOT_USERNAME}
  webhook_url: ${TELEGRAM_WEBHOOK}
```

Pois este arquivo nestes moldes é necessário para o deploy do Ludum e não deve ter suas modificações feitas em repositórios locais commitadas.

2019-06-04 00:57 UTC, guilhermesiqueira approved these changes
Mudanças realizadas. Aprovando!

2019-06-04 00:57 UTC, merged