US08 - Informar sobre formas de contribuição com conteúdo
fga-eps-mds/2019.1-Ludum pull request #163
Opened 2019-06-17 13:51 UTC by lucasgandac

### Descrição:
Eu, como usuário, desejo que o Ludum me informe sobre a possibilidade de contribuição com links.

### Critérios de Aceitação
- [X] O código deve atender a folha de estilo;
- [X] O conteúdo das mensagens está conforme a [personalidade](https://fga-eps-mds.github.io/2019.1-Ludum/#/personalidade-ludum) definida para ele;
- [X] O Ludum deve estar explicando como contribuir com links;
- [X] O Ludum deve estar explicando como contribuir com tutoriais;
- [X] O Ludum deve estar introduzindo a funcionalidade;
- [X] O Ludum deve estar exibindo o link para o webclient, após explicar como contribuir;
- [X] O Ludum deve estar explicando que as contribuições passam por avaliações dos administradores;
- [X] Ao final, deve redirecionar ao menu principal.

### Tarefas
- [X] Exibir mensagem introduzindo brevemente a funcionalidade e ressaltando a importância da contribuição do usuário, ex: _"Você é muito importante para deixar o Ludum cada vez melhor e ajudá-lo a cumprir sua missão... Contribua com nossos conteúdos... É muito simples!"_;
- [X] Exibir mensagem explicando como contribuir com links, ex: _"Se você achou um artigo, um vídeo, um fórum, alguma coisa muito legal relacionado a Pygame que ajude outros usuários em seus estudos e gostaria de que o Ludum o compartilhasse, basta cadastrar esse link em nossos materiais"_;
- [X] Exibir mensagem explicando como contribuir com tutoriais, ex: _"Ou se você desenvolveu um jogo e gostaria de ensinar outros usuários como desenvolvê-lo, se tem algum aspecto acerca da Pygame que seria legal ensinar outros usuários, entre outros, não hesite em contribuir com nossos tutoriais..."_;
- [X] Exibir mensagem explicando que todas as contribuições passam por avaliações da equipe administradora;
- [X] Exibir mensagem com o link do webclient, ex: _"Para cadastrar um desses materiais, acesse o endereço: "_;
- [X] Ao final do fluxo, redirecionar para o menu principal;

### Comentários
Nenhum.

**Estimativa de Duração** : 2 pontos

2019-06-18 20:49 UTC, LucasPenido commented
Por favor, resolva os conflitos para que seja realizado a revisão.

2019-06-20 23:35 UTC, lucasgandac commented
O merge com a nova development foi feita, portanto aparentemente o PR ja esta pronto para ser aceito

2019-06-22 00:36 UTC, guilhermesiqueira requested changes
Atentem-se para o último critério de aceitação -  Ao final, deve redirecionar ao menu principal -, cujo não está sendo cumprido. Por favor, corrija isto escrevendo uma mensagem do tipo: "Podemos voltar ao menu principal?"
<img width="856" alt="Captura de Tela 2019-06-21 às 21 34 16" src="https://user-images.githubusercontent.com/30915713/59957213-8cbbaf80-946c-11e9-95ae-41868c5bf4d1.png">

2019-06-22 21:04 UTC, lucasgandac commented
Pronto, todas os criterios da issue ja foram cumpridos

2019-06-23 00:31 UTC, guilhermesiqueira requested changes
Na primeira vez que o usuário utiliza o bot, quando se clica no botão referente à funcionalidade deste PR, o Ludum está mandando repetitivamente a mensagem do menu principal.  Após escrever alguma mensagem (ou seja, diferente de clicar no botão) a funcionalidade volta a funcionar

<img width="853" alt="Captura de Tela 2019-06-22 às 21 23 11" src="https://user-images.githubusercontent.com/30915713/59970099-b0e2c380-9534-11e9-8188-5ff69de6c370.png">

2019-06-24 01:43 UTC, guilhermesiqueira approved these changes
Tudo ok! Aprovando
<img width="564" alt="Captura de Tela 2019-06-23 às 22 42 43" src="https://user-images.githubusercontent.com/30915713/59985466-3d11eb00-9608-11e9-9236-688b648d11ec.png">

2019-06-24 01:43 UTC, merged