Docs/t07(Documento de Visão)
fga-eps-mds/2019.1-Ludum pull request #21
Opened 2019-03-30 04:28 UTC by Wictorgirardi

## Descrição
Nesse Pull Request (PR) foram resolvidos os seguintes aspectos:
  - Criação do documento de Visão;

## Issue Correspondente
Issue #10 

## Tipo de mudança
- [ ] **Bugfix** (mudança que corrige um problema)
- [x] **Nova funcionalidade** (mudança que adiciona uma funcionalidade)
- [ ] **Mudança de funcionalidade** (corrige ou adiciona recursos de uma funcionalidade que já existe)

## Checklist
Esse PR atende os requisitos abaixo:
- [ ] A definir;
- [ ] A definir;
- [ ] A definir.

## Comentários
Criação e primeira Revisão do documento de visão.

2019-03-30 16:56 UTC, LucasLermen commented
Algumas pequenas correções para o PR ser aceito:
- Alterar de "Alunos da Universidade de Brasília" para "interessados em programação de jogos" onde se diz respeito aos interessados;
- Alterar "Jupyter" para "Ferramenta externa", pois ainda tem de ser decidida.

2019-03-30 17:03 UTC, LucasLermen submitted a review, later dismissed
Algumas pequenas correções para o PR ser aceito:
- Alterar de "Alunos da Universidade de Brasília" para "interessados em programação de jogos" onde se diz respeito aos interessados;
- Alterar "Jupyter" para "Ferramenta externa", pois ainda tem de ser decidida.

2019-03-30 21:50 UTC, gabrielademoraes requested changes
Sugestões de correções.

2019-03-30 21:50 UTC, gabrielademoraes commented on docs/Documento_Visao.md
> +# 1. Introdução
- Justificar o texto (basta usar `<p align="justify">Texto Aqui</p>`).

2019-03-30 21:50 UTC, gabrielademoraes commented on docs/Documento_Visao.md
> +O projeto, a ser realizado pela equipe 8, composta por alunos das duas disciplinas, possui como objetivo auxiliar os alunos da universidade em dúvidas que eles tenham em relação ao desenvolvimento de
- Não somente alunos da universidade, mas sim pessoas interessadas em programação e desenvolvimento de jogos.

2019-03-30 21:50 UTC, gabrielademoraes commented on docs/Documento_Visao.md
> +<tr><th>Para</th><td>Estudantes da área de programação e pessoas interessadas no desenvolvimento de jogos.</td></tr>
- Pessoas interessadas na área de programação e no desenvolvimento de jogos.

2019-03-30 21:50 UTC, gabrielademoraes commented on docs/Documento_Visao.md
> +<tr><th>Que</th><td>Buscam num software uma maneira prática e acessível de aprender e desenvolver um jogo na linguagem Python através da biblioteca  Pygame.</td></tr>
- Buscam em um software

2019-03-30 21:50 UTC, gabrielademoraes commented on docs/Documento_Visao.md
> +O público-alvo do projeto, que irá interagir com o Ludum, são alunos da FGA, sejam eles de graduação ou pós-graduação.
O público alvo não está limitado somente a FGA. São pessoas interessadas em programação e desenvolvimento de jogos.

2019-03-30 21:50 UTC, gabrielademoraes commented on docs/Documento_Visao.md
> +Os principais artefatos que o Ludum propõe é a maior interatividade e facilidade para o desenvolvimento de pessoas não ligadas a software dentro da Universidade de Brasília.
Maior interatividade, facilidade e praticidade para as pessoas que estão iniciando no Python/PyGame.

2019-03-30 21:50 UTC, gabrielademoraes commented on docs/Documento_Visao.md
> +
Não está limitado somente a alunos da FGA.

2019-03-30 21:50 UTC, gabrielademoraes commented on docs/Documento_Visao.md
> +<tr><th>Problemas/comentários</th><td>Não possuir cadastro no Telegram</td></tr>
Não possuir conexão com a internet e hardware não suficiente para executar a aplicação.

2019-03-30 21:50 UTC, gabrielademoraes commented on docs/Documento_Visao.md
> +| Configuração de ambiente | O ChatBot irá auxiliar a antes do desenvolvimento que o ambiente seja configurado de maneira adequada |
Outras funcionalidades são sanar dúvidas com auxílio de um FAQ e indicar links e materiais úteis.

2019-03-30 21:50 UTC, gabrielademoraes commented on docs/Documento_Visao.md
> +# 5. Recursos do Produto
Acrescentar funcionalidade das dúvidas e dos links úteis também.

2019-03-30 21:50 UTC, gabrielademoraes commented on docs/Documento_Visao.md
> +Dar dicas de como configurar o ambiente de desenvolvimento e aplicações úteis ao desenvolvimento para leigos.
Separar "Ensinar como configurar o ambiente" e "Recomendar links e materiais úteis".

2019-03-30 21:50 UTC, gabrielademoraes commented on docs/Documento_Visao.md
> +Esta aplicação deverá ser acessada através de dispositivos que possuem a aplicação Telegram em que o sistema operacional é variável de acordo com o dispositivo de utilização, podendo ser: Android, iO
Acho que poderia retirar as reticências.

2019-04-01 02:48 UTC, gabrielademoraes requested changes
Novas correções.

2019-04-01 02:48 UTC, gabrielademoraes commented on docs/Documento_Visao.md
> +# 1. Introdução
O texto ainda não está justificado.

2019-04-01 02:48 UTC, gabrielademoraes commented on docs/Documento_Visao.md
> +O projeto, a ser realizado pela equipe 8, composta por alunos das duas disciplinas, possui como objetivo auxiliar os interessados em progamações e desenvolvimento de jogos em dúvidas que eles tenham
Substituir "integração a um ambiente de desenvolvimento externo" para "integração a uma ferramenta externa".

2019-04-01 02:48 UTC, gabrielademoraes commented on docs/Documento_Visao.md
> +<tr><th>Nosso Produto</th><td>Responde perguntas sobre o desenvolvimento de jogos em Python, e sua biblioteca Pygame.</td></tr>
Tirar vírgula depois de Python

2019-04-01 02:48 UTC, gabrielademoraes commented on docs/Documento_Visao.md
> +Os principais artefatos que o Ludum propõe é a maior interatividade e facilidade para o desenvolvimento de pessoas não ligadas a software dentro da Universidade de Brasília.
Seguir sugestão de texto acima

2019-04-01 02:48 UTC, gabrielademoraes commented on docs/Documento_Visao.md
> +|Orientador|Professora na Universidade de Brasília, no campus Faculdade Gama (FGA - UnB), atual professora das disciplinas Métodos de Desenvolvimento de Software e Engenharia de Produto de Software.|
"Professoras da Universidade de Brasília no campus Faculdade Gama (FGA - UnB) das disciplinas ..."

2019-04-01 02:48 UTC, gabrielademoraes commented on docs/Documento_Visao.md
> +<tr><th>Tipo</th><td>Estudantes da Universidade de Brasília, da disciplina de engenharia de produtos de software</td></tr>
Disciplina de Engenharia de Produto de Software (EPS)

2019-04-01 02:48 UTC, gabrielademoraes commented on docs/Documento_Visao.md
> +<tr><th>Tipo</th><td>Estudantes da FGA que tenham dúvidas e necessitem de ajuda com o desenvolvimento de jogos em Python</td></tr>
Interessados no desenvolvimento de jogos que tenham dúvidas...

2019-04-01 02:48 UTC, gabrielademoraes commented on docs/Documento_Visao.md
> +|Sanar dúvidas que tangem o quesito de desenvolvimento de jogos em Python|Alta|Falta de interação com o Ludum|Um ChatBot de Telegram que consiga auxiliar os universitários respondendo suas dúvidas e
auxiliar o público alvo respondendo suas ...

2019-04-01 02:48 UTC, gabrielademoraes commented on docs/Documento_Visao.md
> +|Execução de códigos em uma ferramenta externa|Alta|Códigos mal digitados ou em outras linguagens|A identificação de códigos e a rápida execução e debug dentro do chat|Instalar a ferramenta externa n
Esse pedaço da execução em ferramenta externa pode ser retirado

2019-04-01 02:48 UTC, gabrielademoraes commented on docs/Documento_Visao.md
> +| Conexão com uma ferramenta externa | O Ludum possibilitará com que o usuário mande trechos de código para serem compilados de maneira instantânea dentro do chat |
"O Ludum poderá acessar uma ferramenta externa para buscar informações sobre a biblioteca PyGame"

2019-04-01 02:48 UTC, gabrielademoraes commented on docs/Documento_Visao.md
> +| Configuração de ambiente | O ChatBot irá auxiliar a antes do desenvolvimento que o ambiente seja configurado de maneira adequada |
"O ChatBot irá auxiliar o usuário antes do desenvolvimento a configurar o ambiente."

2019-04-01 02:48 UTC, gabrielademoraes commented on docs/Documento_Visao.md
> +
Corrigir "permitirá"  e "materiais"

2019-04-01 02:48 UTC, gabrielademoraes commented on docs/Documento_Visao.md
> +Realizar a integração entre bot, usuário e Jupyter.
Realizar a integração entre bot, usuário e ferramenta externa.

2019-04-01 02:48 UTC, gabrielademoraes commented on docs/Documento_Visao.md
> +O chatbot deverá ser implementado na linguagem Python, com API em Django Rest.
"O ChatBot deverá ser implementado na linguagem Python utilizando a arquitetura de microsserviços".

2019-04-01 02:48 UTC, gabrielademoraes commented on docs/Documento_Visao.md
> +Para maior eficiência, a aplicação será mobile, sendo executada por meio da aplicação de comunicação Telegram, para uma forma segura e rápida de gerenciamento de dados e informações.
"Para maior eficiência, será utilizado por meio da aplicação ... "

2019-04-01 18:48 UTC, gabrielademoraes requested changes
Pequenos ajustes

2019-04-01 18:48 UTC, gabrielademoraes commented on docs/Documento_Visao.md
> +| Configuração de ambiente | O ChatBot irá auxiliar a antes do desenvolvimento que o ambiente seja configurado de maneira adequada |
O tópico de configuração de ambiente ainda está confuso. Sugestão: "O ChatBot irá auxiliar o usuário, antes do desenvolvimento, a configurar o ambiente."

2019-04-01 18:48 UTC, gabrielademoraes commented on docs/Documento_Visao.md
> +O público-alvo do projeto, que irá interagir com o Ludum, são alunos da FGA, sejam eles de graduação ou pós-graduação.
Tirar a parte "alunos da FGA". São pessoas interessadas em programação e desenvolvimento de jogos.

2019-04-01 22:26 UTC, gabrielademoraes approved these changes

2019-04-01 22:27 UTC, merged