Docs/t23
fga-eps-mds/2019.1-Ludum pull request #32
Opened 2019-04-08 02:30 UTC by Wictorgirardi

## Descrição
Nesse Pull Request (PR) foram resolvidos os seguintes aspectos:
  - Criação do documento de arquitetura;

## Issue Correspondente
Colocar issue que esse PR resolve. Ex: ![US00 - Nome da Issue](Colocar aqui o link para ela)

## Tipo de mudança
- [ ] **Bugfix** (mudança que corrige um problema)
- [x] **Nova funcionalidade** (mudança que adiciona uma funcionalidade)
- [ ] **Mudança de funcionalidade** (corrige ou adiciona recursos de uma funcionalidade que já existe)

## Checklist
Esse PR atende os requisitos abaixo:

- [x] Escrito na forma padrão da Língua portuguesa;
- [x] Contém todas as informações necessária a um documento de visão;
- [x] Abrange corretamente todos os aspectos do produto de software.

## Comentários
Criação e primeira Revisão do documento de arquitetura.

2019-04-09 00:53 UTC, gabrielademoraes requested changes
Algumas correções

2019-04-09 00:53 UTC, gabrielademoraes commented on docs/documento-de-arquitetura.md
> +<p  align="justify">  O Ludum tem como principal objetivo auxiliar os alunos que desejam aprender a desenvolver jogos em Python, à partir da utilização de tecnologias de fluxo de conversa e de bancos
O Ludum tem como principal objetivo auxiliar pessoas que desejam aprender a desenvolver jogos em Python, a partir da utilização de tecnologias de fluxo de conversa e de bancos de dados para o registro de usuário. E também servirá como uma ferramenta de auxílio a esse público, podendo ajudar desde a configuração do ambiente, auxílio no desenvolvimento de jogos com tutoriais e uso do código fornecido em ferramentas externas

2019-04-09 00:53 UTC, gabrielademoraes commented on docs/documento-de-arquitetura.md
> +<p  align="justify">&emsp;&emsp; O Rasa Core é um dos componentes importantes dentro da arquitetura do Bot, em associação ao Rasa Core, existe outro componente tecnológico atrelado ao ChatBot: <i>Ras
fluída

2019-04-09 00:53 UTC, gabrielademoraes commented on docs/documento-de-arquitetura.md
> +<p align="justify">&emsp;&emsp;Na parte de arquitetura de micro serviços, foram definidos 4 serviços internos (serviços a serem implementados), e 1 serviço externo (serviço a sere utilizado pelo usuá
serviço a ser

2019-04-09 00:53 UTC, gabrielademoraes commented on docs/documento-de-arquitetura.md
> +<p  align="justify">&emsp;&emsp;Telegram Messenger é um aplicativo de comunicação e bate-papo serviço de mensagens instantâneas baseadas em nuvens. O aplicativo da liberdade para seus usuários desenv
O aplicativo dá liberdade para seus usuários desenvolvedores

2019-04-09 01:10 UTC, LucasPenido commented on docs/documento-de-arquitetura.md
> +<li> <i>Webcrawler</i> do StackOverflow - WebCrawler SO </li>
Não será utilizado um Webcrawler para o StackOverflow. Um Webcrawler é um algoritmo usado para analisar o código de um website em busca de informações, e depois usá-las para gerar insights ou classificar os dados encontrados.
Neste caso será utilizado a API do Stack Exchange, onde ela se conectará com o StackOverflow e assim fará as requisições para achar tópicos referente às dúvidas do usuário.

2019-04-09 01:38 UTC, LucasPenido commented on docs/documento-de-arquitetura.md
> +#### 2.1.1 Serviços Internos
Retirar tópico referente aos microsserviços que supostamente seriam utilizados, já que eles não foram bem definidos e ainda falta ser discutidos para que se possa chegar à uma estruturação final.

2019-04-09 01:38 UTC, LucasPenido commented on docs/documento-de-arquitetura.md
> +<p  align="justify">&emsp;&emsp;As <i>APIs</i> dessas duas plataformas serão as pontes de comunicação com o usuário. A partir da implementação e integração do código-fonte com o <i>Rasa NLU</i>, o Te
Utilizaremos apenas uma plataforma...

2019-04-09 01:38 UTC, LucasPenido commented on docs/documento-de-arquitetura.md
> +##### 2.3 Representação dos Serviços
O mesmo avaliado no tópico 2.1 vale para este.

2019-04-14 03:16 UTC, LucasPenido requested changes

2019-04-14 03:16 UTC, LucasPenido commented on docs/documento-de-arquitetura.md
> +<li> MDS: Método de D</li>
Métodos de Desenvolvimento de Software

2019-04-14 03:16 UTC, LucasPenido commented on docs/documento-de-arquitetura.md
> +<p  align="justify">&emsp;&emsp;O Rasa Core é um dos componentes importantes dentro da arquitetura do Bot, em associação ao Rasa Core, existe outro componente tecnológico atrelado ao ChatBot: <i>Rasa
Reescrever para:
O Rasa Core é um dos componentes importantes dentro da arquitetura do Bot. Em associação a ele.

2019-04-14 03:16 UTC, LucasPenido commented on docs/documento-de-arquitetura.md
> +### 2.1.2 Serviços Externos
Adicionar a API do StackExchange.

2019-04-14 03:16 UTC, LucasPenido commented on docs/documento-de-arquitetura.md
> +* <i>Webcrawler</i> do StackOverflow - <i>WebCrawler SO</i>
Não será criado um Webcrawler já que iremos utilizar a API do StackExchange para realizar as buscas dentro do StackOverflow.

2019-04-14 03:16 UTC, LucasPenido commented on docs/documento-de-arquitetura.md
> +&emsp;&emsp;Além disso, temos o core do projeto, que apesar da relevância, uma suposta falha não afeta o funcionamento dos demais serviços existes. O Ludum, tem a capacidade de fazer, atualmente, uma
Na verdade, caso o core do sistema falha, todos os outros serviços serão afetados. São criados microsserviços justamente para caso de algum falhar, não afetar um outro.

2019-04-14 03:16 UTC, LucasPenido commented on docs/documento-de-arquitetura.md
> +<p align="justify">&emsp;&emsp;A respeito da estrutura geral do banco associado ao WebCrawler SO, temos a seguinte diagramação:</p>
Como dito a cima, não utilizaremos um WebCrawler.
Cada microsserviço terá um BD individual.

2019-04-14 03:16 UTC, LucasPenido commented on docs/documento-de-arquitetura.md
> +<li>Fornecer ao usuário uma maneira de executar seus códigos em uma ferramenta externa.</li>
Esta funcionalidade não está no escopo do produto.

2019-04-14 03:16 UTC, LucasPenido commented on docs/documento-de-arquitetura.md
> +<p align="justify">&emsp;&emsp;As metas do projeto são:</p>
Adicionar a meta de que o bot deverá ensinar o usuário a criar jogos com diferentes níveis de dificuldade.

2019-04-14 03:22 UTC, LucasPenido requested changes

2019-04-14 03:22 UTC, LucasPenido commented on docs/documento-de-arquitetura.md
> +<p  align="justify">&emsp;&emsp;A <i>API</i> dessa plataforma será as pontes de comunicação com o usuário. A partir da implementação e integração do código-fonte com o <i>Rasa NLU</i>, o Telegram irá
Arrumar para:
será **a ponte**...

2019-04-14 04:06 UTC, LucasPenido commented on docs/documento-de-arquitetura.md
> +&emsp;&emsp;Além disso, temos o core do projeto, que apesar da relevância, uma suposta falha não afeta o funcionamento dos demais serviços existes. O Ludum, tem a capacidade de fazer, atualmente, uma
O comentário à cima é apenas uma explicação, deve-se refatorar o documento para que possa ser entendido isto.

2019-04-14 13:58 UTC, LucasPenido requested changes

2019-04-14 13:58 UTC, LucasPenido commented on docs/documento-de-arquitetura.md
> +&emsp;&emsp;Além disso, temos o core do projeto, que apesar da relevância, uma suposta falha não afeta o funcionamento dos demais serviços existes. O Ludum, tem a capacidade de fazer, atualmente, uma
Pode colocar assim:
Além disso, temos o core do projeto, que junto com microsserviços bem definidos evitará que caso algum deles falhe, não afete os outros e nem o core.

2019-04-14 15:54 UTC, LucasPenido commented
Documento disponível em https://fga-eps-mds.github.io/2019.1-Ludum/#/documento-de-arquitetura

2019-04-14 15:58 UTC, merged